Repository SwEnt-Group13/Unio, pull requests merged in 2024-11, with the labels that each got.

#157 Chore/refactor tests and viewmodel cleanup part 2
  app/src/androidTest/java/com/android/unio/ui/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/unio/ui/ScreenDisplayingTest.kt
  app/src/androidTest/java/com/android/unio/ui/association/AssociationProfileTest.kt
  app/src/androidTest/java/com/android/unio/ui/association/EditAssociationTest.kt
  app/src/androidTest/java/com/android/unio/ui/authentication/WelcomeTest.kt
  app/src/androidTest/java/com/android/unio/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/android/unio/ui/settings/SettingsTest.kt
  app/src/androidTest/java/com/android/unio/ui/user/UserProfileTest.kt
  app/src/main/java/com/android/unio/model/association/AssociationViewModel.kt
  app/src/main/java/com/android/unio/model/firestore/transform/Hydration.kt
  app/src/main/java/com/android/unio/model/firestore/transform/Serialization.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/AssociationTestTags.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/AuthenticationTestTags.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/MapTestTags.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/NavigationTestTags.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/SavedTestTags.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/SettingsTestTags.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/UserTestTags.kt
  app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt
  app/src/main/java/com/android/unio/ui/association/EditAssociation.kt
  app/src/main/java/com/android/unio/ui/authentication/EmailVerification.kt
  app/src/main/java/com/android/unio/ui/authentication/Welcome.kt
  app/src/main/java/com/android/unio/ui/map/Map.kt
  app/src/main/java/com/android/unio/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/unio/ui/saved/Saved.kt
  app/src/main/java/com/android/unio/ui/settings/Settings.kt
  app/src/main/java/com/android/unio/ui/user/SomeoneElseUserProfile.kt
  app/src/main/java/com/android/unio/ui/user/UserProfile.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/unio/model/association/AssociationRepositoryFirestoreTest.kt
  app/src/test/java/com/android/unio/model/association/AssociationViewModelTest.kt
  app/src/test/java/com/android/unio/model/event/EventRepositoryFirestoreTest.kt
  app/src/test/java/com/android/unio/model/event/EventRepositoryInitTest.kt
  app/src/test/java/com/android/unio/model/user/UserRepositoryFirestoreTest.kt
Labels: refactor

#156 Implement following mechanism
  app/build.gradle.kts
  app/src/androidTest/java/com/android/unio/ui/ScreenDisplayingTest.kt
  app/src/androidTest/java/com/android/unio/ui/association/AssociationProfileTest.kt
  app/src/androidTest/java/com/android/unio/ui/explore/ExploreScreenTest.kt
  app/src/main/java/com/android/unio/model/association/AssociationRepository.kt
  app/src/main/java/com/android/unio/model/association/AssociationRepositoryFirestore.kt
  app/src/main/java/com/android/unio/model/association/AssociationViewModel.kt
  app/src/main/java/com/android/unio/model/firestore/transform/Hydration.kt
  app/src/main/java/com/android/unio/model/follow/ConcurrentAssociationUserRepository.kt
  app/src/main/java/com/android/unio/model/follow/ConcurrentAssociationUserRepositoryFirestore.kt
  app/src/main/java/com/android/unio/model/hilt/module/HiltModule.kt
  app/src/main/java/com/android/unio/model/user/User.kt
  app/src/main/java/com/android/unio/model/user/UserRepository.kt
  app/src/main/java/com/android/unio/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/unio/model/association/AssociationViewModelTest.kt
Labels: enhancement

#164 Feat/map: user gps location
  app/build.gradle.kts
  app/src/androidTest/java/com/android/unio/ui/ScreenDisplayingTest.kt
  app/src/androidTest/java/com/android/unio/ui/map/MapScreenTest.kt
  app/src/main/java/com/android/unio/MainActivity.kt
  app/src/main/java/com/android/unio/model/hilt/module/HiltModule.kt
  app/src/main/java/com/android/unio/model/map/MapViewModel.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/MapTestTags.kt
  app/src/main/java/com/android/unio/ui/map/Map.kt
  app/src/main/java/com/android/unio/ui/theme/Color.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/unio/model/map/MapViewModelTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#180 Minor end-to-end testing utilities
  app/build.gradle.kts
  app/src/androidTest/java/com/android/unio/end2end/EndToEndTest.kt
Labels: enhancement

#179 Link followed event to the frontend
  app/src/androidTest/java/com/android/unio/end2end/EndToEndTest.kt
  app/src/androidTest/java/com/android/unio/ui/HiltModules.kt
  app/src/androidTest/java/com/android/unio/ui/home/HomeTest.kt
  app/src/main/java/com/android/unio/model/event/EventViewModel.kt
  app/src/main/java/com/android/unio/model/user/UserViewModel.kt
  app/src/main/java/com/android/unio/ui/home/Home.kt
  firebase.json
  functions/package-lock.json
Labels: enhancement

#182 Feat/map gps refresh
  app/src/main/java/com/android/unio/model/map/MapViewModel.kt
  app/src/main/java/com/android/unio/ui/map/Map.kt
  app/src/test/java/com/android/unio/model/map/MapViewModelTest.kt
Labels: enhancement

#163 Feat/permissions & access rights
  .github/workflows/ci.yml
  app/build.gradle.kts
  app/src/androidTest/java/com/android/unio/end2end/AssociationProfileE2ETest.kt
  app/src/androidTest/java/com/android/unio/end2end/ClaimAdminRightsTest.kt
  app/src/androidTest/java/com/android/unio/end2end/EndToEndTest.kt
  app/src/androidTest/java/com/android/unio/end2end/SearchTest.kt
  app/src/androidTest/java/com/android/unio/ui/ScreenDisplayingTest.kt
  app/src/androidTest/java/com/android/unio/ui/authentication/WelcomeTest.kt
  app/src/androidTest/java/com/android/unio/ui/user/UserClaimAssociationPresidentialRightsTest.kt
  app/src/androidTest/java/com/android/unio/ui/user/UserClaimAssociationTest.kt
  app/src/androidTest/java/com/android/unio/ui/user/UserProfileTest.kt
  app/src/main/java/com/android/unio/MainActivity.kt
  app/src/main/java/com/android/unio/mocks/association/MockAssociation.kt
  app/src/main/java/com/android/unio/model/association/Association.kt
  app/src/main/java/com/android/unio/model/firestore/transform/Hydration.kt
  app/src/main/java/com/android/unio/model/firestore/transform/Serialization.kt
  app/src/main/java/com/android/unio/model/strings/Strings.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/UserTestTags.kt
  app/src/main/java/com/android/unio/model/user/User.kt
  app/src/main/java/com/android/unio/ui/association/AssociationSearchBar.kt
  app/src/main/java/com/android/unio/ui/association/EditAssociation.kt
  app/src/main/java/com/android/unio/ui/explore/Explore.kt
  app/src/main/java/com/android/unio/ui/navigation/NavigationAction.kt
  app/src/main/java/com/android/unio/ui/user/SomeoneElseUserProfile.kt
  app/src/main/java/com/android/unio/ui/user/UserClaimAssociation.kt
  app/src/main/java/com/android/unio/ui/user/UserClaimAssociationPresidentialRights.kt
  app/src/main/java/com/android/unio/ui/user/UserProfile.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/unio/model/association/AssociationRepositoryFirestoreTest.kt
  app/src/test/java/com/android/unio/model/firestore/HydrationAndSerializationTest.kt
  app/src/test/java/com/android/unio/model/search/SearchRepositoryTest.kt
  firebase.json
  firebase/emulator-data/auth_export/accounts.json
  firebase/emulator-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  firebase/emulator-data/firestore_export/all_namespaces/all_kinds/output-0
  firebase/emulator-data/firestore_export/firestore_export.overall_export_metadata
  firestore.rules
  functions/.eslintrc.js
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
  gradle/libs.versions.toml
  gradlew
Labels: enhancement

#214 Adapt the "following" feature to work in offline mode
  app/src/androidTest/java/com/android/unio/components/association/AssociationProfileTest.kt
  app/src/main/java/com/android/unio/model/utils/Utils.kt
  app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt
  app/src/main/java/com/android/unio/ui/authentication/Welcome.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#224 Feat/geocoder location nominatim
  app/build.gradle.kts
  app/src/androidTest/java/com/android/unio/components/ScreenDisplayingTest.kt
  app/src/androidTest/java/com/android/unio/components/event/EventCreationTest.kt
  app/src/main/java/com/android/unio/MainActivity.kt
  app/src/main/java/com/android/unio/model/hilt/module/HiltModule.kt
  app/src/main/java/com/android/unio/model/map/LocationRepository.kt
  app/src/main/java/com/android/unio/model/map/nominatim/NominatimApiService.kt
  app/src/main/java/com/android/unio/model/map/nominatim/NominatimLocationRepository.kt
  app/src/main/java/com/android/unio/model/map/nominatim/NominatimLocationResponse.kt
  app/src/main/java/com/android/unio/model/map/nominatim/NominatimLocationSearchViewModel.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/AssociationTestTags.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/EventTestTags.kt
  app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt
  app/src/main/java/com/android/unio/ui/event/EventCreation.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/unio/model/map/nominatim/NominatimLocationRepositoryTest.kt
  gradle/libs.versions.toml
Labels: enhancement
