Repository SwEnt-Group13/Unio, pull requests merged in 2024-12, with the labels that each got.

#234 Fix/edit profile offline
  app/src/androidTest/java/com/android/unio/components/user/UserProfileEditionTest.kt
  app/src/main/java/com/android/unio/ui/user/UserProfileEdition.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#236 Make search bars work (at normal speed) in offline mode
  app/src/main/java/com/android/unio/model/association/AssociationRepositoryFirestore.kt
  app/src/main/java/com/android/unio/model/event/EventRepositoryFirestore.kt
  app/src/main/java/com/android/unio/model/firestore/FirestoreUtils.kt
  app/src/main/java/com/android/unio/ui/association/AssociationSearchBar.kt
  app/src/main/java/com/android/unio/ui/user/UserClaimAssociationPresidentialRights.kt
  app/src/main/java/com/android/unio/ui/user/UserProfile.kt
  app/src/test/java/com/android/unio/model/association/AssociationRepositoryFirestoreTest.kt
  app/src/test/java/com/android/unio/model/search/SearchRepositoryTest.kt
  firebase/emulator-data/auth_export/accounts.json
  firebase/emulator-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  firebase/emulator-data/firestore_export/all_namespaces/all_kinds/output-0
  firebase/emulator-data/firestore_export/firestore_export.overall_export_metadata
  package-lock.json
  package.json
Labels: bug

#240 Feature/edit with nominatim
  app/src/androidTest/java/com/android/unio/components/event/EventEditTests.kt
  app/src/main/java/com/android/unio/MainActivity.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/EventTestTags.kt
  app/src/main/java/com/android/unio/ui/components/EventEditComponents.kt
  app/src/main/java/com/android/unio/ui/event/EventCreation.kt
  app/src/main/java/com/android/unio/ui/event/EventEdit.kt
Labels: enhancement

#243 Make saving an event faster and smoother (both online and offline mode)
  app/src/androidTest/java/com/android/unio/components/event/EventCardTest.kt
  app/src/main/java/com/android/unio/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/android/unio/model/user/UserViewModel.kt
  app/src/main/java/com/android/unio/ui/event/EventCard.kt
  app/src/main/java/com/android/unio/ui/saved/Saved.kt
  app/src/test/java/com/android/unio/model/user/AuthTest.kt
  app/src/test/java/com/android/unio/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/android/unio/model/user/UserTest.kt
  app/src/test/java/com/android/unio/model/user/UserViewModelTest.kt
Labels: bug

#250 Feat/event creation offline
  app/src/androidTest/java/com/android/unio/components/association/AssociationProfileTest.kt
  app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt
Labels: bug, enhancement

#252 Create an ImageViewModel
  app/src/androidTest/java/com/android/unio/HiltTestUtility.kt
  app/src/androidTest/java/com/android/unio/components/ScreenDisplayingTest.kt
  app/src/androidTest/java/com/android/unio/components/authentication/AccountDetailsTest.kt
  app/src/main/java/com/android/unio/MainActivity.kt
  app/src/main/java/com/android/unio/model/image/ImageRepositoryFirebaseStorage.kt
  app/src/main/java/com/android/unio/model/image/ImageViewModel.kt
  app/src/main/java/com/android/unio/model/preferences/AppPreferences.kt
  app/src/main/java/com/android/unio/ui/authentication/AccountDetails.kt
  app/src/main/java/com/android/unio/ui/theme/Theme.kt
  app/src/main/java/com/android/unio/ui/user/UserProfileEdition.kt
  app/src/test/java/com/android/unio/model/image/ImageViewModelTest.kt
Labels: enhancement

#274 Docs/add missing coments#2
  app/src/androidTest/java/com/android/unio/components/user/UserProfileEditionTest.kt
  app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt
  app/src/main/java/com/android/unio/ui/association/AssociationSearchBar.kt
  app/src/main/java/com/android/unio/ui/association/AssociationSmall.kt
  app/src/main/java/com/android/unio/ui/association/EditAssociation.kt
  app/src/main/java/com/android/unio/ui/authentication/AccountDetails.kt
  app/src/main/java/com/android/unio/ui/authentication/EmailVerification.kt
  app/src/main/java/com/android/unio/ui/authentication/ResetPassword.kt
  app/src/main/java/com/android/unio/ui/authentication/Welcome.kt
  app/src/main/java/com/android/unio/ui/authentication/overlay/InterestOverlay.kt
  app/src/main/java/com/android/unio/ui/authentication/overlay/SocialOverlay.kt
  app/src/main/java/com/android/unio/ui/components/UserEditionComponents.kt
  app/src/main/java/com/android/unio/ui/event/EventCard.kt
  app/src/main/java/com/android/unio/ui/event/EventCreation.kt
  app/src/main/java/com/android/unio/ui/event/EventDetails.kt
  app/src/main/java/com/android/unio/ui/event/overlay/AssociationsOverlay.kt
  app/src/main/java/com/android/unio/ui/explore/Explore.kt
  app/src/main/java/com/android/unio/ui/home/Home.kt
  app/src/main/java/com/android/unio/ui/image/AsyncImageWrapper.kt
  app/src/main/java/com/android/unio/ui/map/Map.kt
  app/src/main/java/com/android/unio/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/unio/ui/navigation/NavigationAction.kt
  app/src/main/java/com/android/unio/ui/saved/Saved.kt
  app/src/main/java/com/android/unio/ui/settings/Settings.kt
  app/src/main/java/com/android/unio/ui/theme/Theme.kt
  app/src/main/java/com/android/unio/ui/user/SomeoneElseUserProfile.kt
  app/src/main/java/com/android/unio/ui/user/UserClaimAssociation.kt
  app/src/main/java/com/android/unio/ui/user/UserProfile.kt
  app/src/main/java/com/android/unio/ui/user/UserProfileEdition.kt
Labels: documentation

#258 Notification Broadcast
  app/src/androidTest/java/com/android/unio/components/ScreenDisplayingTest.kt
  app/src/androidTest/java/com/android/unio/components/association/AssociationProfileBottomSheetTest.kt
  app/src/androidTest/java/com/android/unio/components/association/AssociationProfileTest.kt
  app/src/androidTest/java/com/android/unio/components/event/EventCardTest.kt
  app/src/androidTest/java/com/android/unio/components/event/EventDetailsTest.kt
  app/src/androidTest/java/com/android/unio/components/home/HomeTest.kt
  app/src/androidTest/java/com/android/unio/components/notification/NotificationSenderTest.kt
  app/src/androidTest/java/com/android/unio/components/saved/SavedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/unio/model/association/Association.kt
  app/src/main/java/com/android/unio/model/association/AssociationViewModel.kt
  app/src/main/java/com/android/unio/model/authentication/AuthStateListeners.kt
  app/src/main/java/com/android/unio/model/firestore/transform/Serialization.kt
  app/src/main/java/com/android/unio/model/hilt/module/HiltModule.kt
  app/src/main/java/com/android/unio/model/notification/CloudMessaging.kt
  app/src/main/java/com/android/unio/model/notification/NotificationScheduler.kt
  app/src/main/java/com/android/unio/model/preferences/AppPreferences.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/AssociationTestTags.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/EventTestTags.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/NotificationSenderTestTags.kt
  app/src/main/java/com/android/unio/model/user/UserViewModel.kt
  app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt
  app/src/main/java/com/android/unio/ui/components/NotificationSender.kt
  app/src/main/java/com/android/unio/ui/event/EventCard.kt
  app/src/main/java/com/android/unio/ui/event/EventDetails.kt
  app/src/main/java/com/android/unio/ui/settings/Settings.kt
  app/src/main/java/com/android/unio/ui/user/UserClaimAssociationPresidentialRights.kt
  app/src/main/java/com/android/unio/ui/user/UserProfile.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/unio/model/association/AssociationRepositoryFirestoreTest.kt
  app/src/test/java/com/android/unio/model/authentication/AuthViewModelTest.kt
  app/src/test/java/com/android/unio/model/event/EventRepositoryFirestoreTest.kt
  app/src/test/java/com/android/unio/model/notification/BroadcastMessageTest.kt
  app/src/test/java/com/android/unio/model/notification/UnioMessagingServiceTest.kt
  app/src/test/java/com/android/unio/model/user/UserRepositoryFirestoreTest.kt
  functions/index.js
Labels: enhancement

#287 Rework some functions/variables
  app/src/androidTest/java/com/android/unio/components/ScreenDisplayingTest.kt
  app/src/androidTest/java/com/android/unio/components/association/AssociationProfileTest.kt
  app/src/androidTest/java/com/android/unio/components/event/EventCreationTest.kt
  app/src/androidTest/java/com/android/unio/components/event/EventEditTests.kt
  app/src/main/java/com/android/unio/model/association/AssociationViewModel.kt
  app/src/main/java/com/android/unio/model/event/EventRepository.kt
  app/src/main/java/com/android/unio/model/event/EventRepositoryFirestore.kt
  app/src/main/java/com/android/unio/ui/map/Map.kt
  app/src/main/java/com/android/unio/ui/saved/Saved.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/unio/model/association/AssociationViewModelTest.kt
  app/src/test/java/com/android/unio/model/event/EventRepositoryFirestoreTest.kt
Labels: refactor

#272 Feat/event address button marker focus
  app/src/androidTest/java/com/android/unio/components/event/EventDetailsTest.kt
  app/src/androidTest/java/com/android/unio/components/map/MapScreenTest.kt
  app/src/main/java/com/android/unio/model/map/MapViewModel.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/event/EventTestTags.kt
  app/src/main/java/com/android/unio/ui/event/EventDetails.kt
  app/src/main/java/com/android/unio/ui/map/Map.kt
  app/src/test/java/com/android/unio/model/map/MapViewModelTest.kt
Labels: enhancement, refactor

#290 Polish Association profile
  app/src/androidTest/java/com/android/unio/components/association/AssociationProfileTest.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/association/AssociationTestTags.kt
  app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: refactor

#288 Rework Claim Association
  app/src/androidTest/java/com/android/unio/components/user/UserClaimAssociationTest.kt
  app/src/main/java/com/android/unio/model/firestore/transform/Serialization.kt
  app/src/main/java/com/android/unio/ui/user/UserClaimAssociation.kt
  app/src/main/java/com/android/unio/ui/user/UserClaimAssociationPresidentialRights.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/unio/model/firestore/HydrationAndSerializationTest.kt
Labels: refactor

#314 Add highlighting to missing inputs in Event creation and Event edition
  app/src/main/java/com/android/unio/ui/components/EventEditComponents.kt
  app/src/main/java/com/android/unio/ui/event/EventCreation.kt
  app/src/main/java/com/android/unio/ui/event/EventEdit.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#307 Chore/figma adaptations
  app/src/androidTest/java/com/android/unio/components/authentication/AccountDetailsTest.kt
  app/src/androidTest/java/com/android/unio/components/event/EventCreationTest.kt
  app/src/androidTest/java/com/android/unio/components/event/EventEditTests.kt
  app/src/androidTest/java/com/android/unio/components/user/UserProfileEditionTest.kt
  app/src/androidTest/java/com/android/unio/end2end/EventCreationE2ETest.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/authentication/AuthenticationTestTags.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/event/EventTestTags.kt
  app/src/main/java/com/android/unio/model/strings/test_tags/user/UserEditionTestTags.kt
  app/src/main/java/com/android/unio/ui/authentication/AccountDetails.kt
  app/src/main/java/com/android/unio/ui/components/EventEditComponents.kt
  app/src/main/java/com/android/unio/ui/event/EventCreation.kt
  app/src/main/java/com/android/unio/ui/event/EventEdit.kt
  app/src/main/java/com/android/unio/ui/user/UserProfileEdition.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, refactor

#297 Pull to refresh indicators
  .github/workflows/ci.yml
  app/src/androidTest/java/com/android/unio/Utils.kt
  app/src/androidTest/java/com/android/unio/components/event/EventDetailsTest.kt
  app/src/androidTest/java/com/android/unio/end2end/EventCreationE2ETest.kt
  app/src/main/java/com/android/unio/model/association/AssociationRepository.kt
  app/src/main/java/com/android/unio/model/association/AssociationRepositoryFirestore.kt
  app/src/main/java/com/android/unio/model/association/AssociationViewModel.kt
  app/src/main/java/com/android/unio/model/event/EventViewModel.kt
  app/src/main/java/com/android/unio/model/firestore/FirestoreReferenceElement.kt
  app/src/main/java/com/android/unio/model/firestore/FirestoreReferenceList.kt
  app/src/main/java/com/android/unio/model/search/SearchRepository.kt
  app/src/main/java/com/android/unio/ui/association/AssociationProfile.kt
  app/src/main/java/com/android/unio/ui/event/EventDetails.kt
  app/src/main/java/com/android/unio/ui/explore/Explore.kt
  app/src/main/java/com/android/unio/ui/home/Home.kt
  app/src/main/java/com/android/unio/ui/saved/Saved.kt
  app/src/test/java/com/android/unio/model/association/AssociationRepositoryFirestoreTest.kt
  app/src/test/java/com/android/unio/model/search/SearchRepositoryTest.kt
Labels: enhancement

#321 Chore/Figma adaptations pt2
  app/src/main/java/com/android/unio/model/strings/test_tags/authentication/AuthenticationTestTags.kt
  app/src/main/java/com/android/unio/ui/authentication/Welcome.kt
  app/src/main/java/com/android/unio/ui/map/Map.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, refactor
